// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectcomparator.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import objectcomparator.helpers.Comparator;
import objectcomparator.repositories.MendixObjectRepository;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ObjectComparator extends UserAction<java.lang.Boolean>
{
	private final IMendixObject ExpectedObject;
	private final IMendixObject ActualObject;
	private final java.lang.Boolean IncludeAssociatedObjects;

	public ObjectComparator(
		IContext context,
		IMendixObject _expectedObject,
		IMendixObject _actualObject,
		java.lang.Boolean _includeAssociatedObjects
	)
	{
		super(context);
		this.ExpectedObject = _expectedObject;
		this.ActualObject = _actualObject;
		this.IncludeAssociatedObjects = _includeAssociatedObjects;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger("ObjectComparator");
		MendixObjectRepository mendixObjectRepository = new MendixObjectRepository(getContext());
		Comparator comparator = new Comparator(ExpectedObject, ActualObject, logger, mendixObjectRepository, IncludeAssociatedObjects);
		return comparator.CompareLists();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ObjectComparator";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
